Insert Into role values(1,'admin')
Insert Into role values(2,'store_manager')
Insert Into role values(3,'merchandiger')
Insert Into role values(4,'managing_director')
Insert Into role values(4,'general_manager')
